name: Get translations
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/translate.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test
      - run: git add test.json
      - run: git commit -m "Added test.json"
      - run: git push origin main
