name: Get translations
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/translate.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
      - name: Get data
        run: |
          npm install
          npm run test
      - name: Commit report
        run: |
          git config --global user.name 'alsino'
          git config --global user.email 'iamahorse@gmail.com'
          git add test.json
          git commit -m "Added test.json"
          git push
